//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGFBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gratificacaoFiscalTipoLiberacao
    {
        public int num_tipo_liberacao { get; set; }
        public string desc_tipo_liberacao { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public Nullable<System.DateTime> data_atualizacao { get; set; }
    }
}
