//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGFBack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GfEntities1 : DbContext
    {
        public GfEntities1()
            : base("name=GfEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gratificacaoFiscalTipoLiberacao> gratificacaoFiscalTipoLiberacao { get; set; }
        public virtual DbSet<servidor> servidor { get; set; }
        public virtual DbSet<gratificacaoFiscalAtoLiberacaoProcesso> gratificacaoFiscalAtoLiberacaoProcesso { get; set; }
    }
}
