//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGFBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servidor
    {
        public int num_servidor { get; set; }
        public string nome_servidor { get; set; }
        public string num_processo { get; set; }
    }
}
